# Note: All operators are binary operators. For more than two operands, you may use the nested parentheses trick.
# For example:
#    *  A == 1 or (B == 2 and C in [1,2,3])
#    *  (A == 1 and B == 2) or (C not in ["3", "4", 5])

# Test apps
test_apps/lcd/3wire_spi_rgb:
  disable:
    - if: SOC_LCD_RGB_SUPPORTED != 1
    - if: IDF_TARGET == "esp32p4"
      temporary: true
      reason: not ready

test_apps/lcd/qspi:
  disable:
    - if: SOC_GPSPI_SUPPORTED != 1

test_apps/lcd/rgb:
  disable:
    - if: SOC_LCD_RGB_SUPPORTED != 1
    - if: IDF_TARGET == "esp32p4"
      temporary: true
      reason: not ready

test_apps/lcd/spi:
  disable:
    - if: SOC_GPSPI_SUPPORTED != 1

test_apps/panel:
  enable:
    - if: INCLUDE_DEFAULT == 1

test_apps/touch/i2c:
  disable:
    - if: SOC_I2C_SUPPORTED != 1

test_apps/touch/spi:
  disable:
    - if: SOC_GPSPI_SUPPORTED != 1

# Examples
# examples/esp_idf/esp_brookesia_phone_m5stace_core_s3:
#   enable:
#     - if: IDF_TARGET in ["esp32s3"]
