// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Porting

#include "../ui.h"

void ui_Screen_screen_init(void)
{
ui_Screen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHelloWorld = lv_label_create(ui_Screen);
lv_obj_set_width( ui_LabelHelloWorld, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHelloWorld, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHelloWorld, 0 );
lv_obj_set_y( ui_LabelHelloWorld, -92 );
lv_obj_set_align( ui_LabelHelloWorld, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHelloWorld,"Hello World!");
lv_obj_set_style_text_font(ui_LabelHelloWorld, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button = lv_btn_create(ui_Screen);
lv_obj_set_width( ui_Button, 80);
lv_obj_set_height( ui_Button, 50);
lv_obj_set_x( ui_Button, -9 );
lv_obj_set_y( ui_Button, 71 );
lv_obj_set_align( ui_Button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button, 80, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button, lv_color_hex(0xDDD7D7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Labelbtn = lv_label_create(ui_Button);
lv_obj_set_width( ui_Labelbtn, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labelbtn, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Labelbtn, LV_ALIGN_CENTER );
lv_label_set_text(ui_Labelbtn,"Click me");
lv_obj_set_style_text_color(ui_Labelbtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Labelbtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Labelbtn, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ArcNum = lv_arc_create(ui_Screen);
lv_obj_set_width( ui_ArcNum, 91);
lv_obj_set_height( ui_ArcNum, 87);
lv_obj_set_x( ui_ArcNum, -7 );
lv_obj_set_y( ui_ArcNum, -16 );
lv_obj_set_align( ui_ArcNum, LV_ALIGN_CENTER );
lv_arc_set_value(ui_ArcNum, 10);
lv_obj_set_style_arc_width(ui_ArcNum, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_ArcNum, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ArcNum, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArcNum, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button, ui_event_Button, LV_EVENT_ALL, NULL);

}
