// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Porting

#ifndef _SQUARELINE_PORTING_UI_H
#define _SQUARELINE_PORTING_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen
void ui_Screen_screen_init(void);
extern lv_obj_t *ui_Screen;
extern lv_obj_t *ui_LabelHelloWorld;
void ui_event_Button( lv_event_t * e);
extern lv_obj_t *ui_Button;
extern lv_obj_t *ui_Labelbtn;
extern lv_obj_t *ui_ArcNum;
extern lv_obj_t *ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
