// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: ArduinoDemo

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Factory_cb(lv_event_t * e);
void Ala_confirm_cb(lv_event_t * e);
void ButtonAlarm_cb(lv_event_t * e);
void ButtonSetWifi_cb(lv_event_t * e);
void ButtonRetSet_cb(lv_event_t * e);
void ButtonRetWifi_cb(lv_event_t * e);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
