name: Build Test Application

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        idf_ver: ["v4.4.5"]
        sdkconfig_defaults:
          [
            "sdkconfig.defaults.esp32_c3_lcdkit",
            "sdkconfig.defaults.esp32_s3_box",
            "sdkconfig.defaults.esp32_s3_box_3",
            "sdkconfig.defaults.esp32_s3_box_lite",
            "sdkconfig.defaults.esp32_s3_eye",
            "sdkconfig.defaults.esp32_s3_korvo_2",
            "sdkconfig.defaults.esp32_s3_lcd_ev_board",
            "sdkconfig.defaults.esp32_s3_lcd_ev_board_2",
            "sdkconfig.defaults.esp32_s3_otg",
          ]
    runs-on: ubuntu-20.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v3
      - name: Build ESP32_Display_Panel Test Application
        env:
          SDKCONFIG_DEFAULTS: ${{ matrix.sdkconfig_defaults }}
        working-directory: test_apps
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          export PEDANTIC_FLAGS="-DIDF_CI_BUILD -Werror -Werror=deprecated-declarations -Werror=unused-variable -Werror=unused-but-set-variable -Werror=unused-function"
          export EXTRA_CFLAGS="${PEDANTIC_FLAGS} -Wstrict-prototypes"
          export EXTRA_CXXFLAGS="${PEDANTIC_FLAGS}"
          cat ${SDKCONFIG_DEFAULTS} > sdkconfig.defaults
          idf.py build